### ISSUE TITLE
arklet and sofaark 日志配置支持 logging.file.path 

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#128]
## 问题
logging 需要支持 logging.file.path, logging.path 在 springboot 2.3.x 后已经去除，sofaArk 与 Arklet 需要支持使用配置 logging.file.path

## 影响
1. 新用户接入，一般只配置 logging.file.path，会导致无法打印 sofaArk 与 Arklet 日志到目录里，这类将无法查看日志，需要用户排查然后同时配置 logging.file.path 与 logging.path.

## 方案
SOFAArk 与 Arklet 同时支持 logging.file.path 与 logging.path，这样不同版本的 springboot 只需要配置一个日志配置路径即可

Arklet 相关日志配置处：
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/744c585e-288d-45bf-b11d-0bee1441882f)

SOFAArk 相关日志配置处：
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/b927c89a-4191-4fb9-b3a4-b3a329a40cf4)

**Comment by zjulbj** [comment]
sofa-serverless依赖了log-sofa-boot-3.2.0.jar，sofa-common-tools-1.0.19.jar这个两个包来打印日志，强制指定了System Property来设置logging.path，最好放在这两个包里面兼容

**Comment by HzjNeverStop** [comment]
这里 sdk 中的 logging.path 和 springboot 的 logging.file.path 不是一个概念

sdk 中的 logging.path 作用于 sofa-common-tools 创建的各个独立 logContext，springboot 的日志配置 (低版本 loging.path/ 高版本 logging.file.path) 作用于应用默认 slf4j 的 logContext，互不干扰。

sofaboot 及 sofastack 相关 sdk 使用的 log 配置中均使用 logging.path，只配置 logging.file.path 将导致这些 sdk 使用默认值。

这个问题只需要用户额外配置一个 logging.path=${logging.file.path} 即可

**Comment by zjulbj** [comment]
> logging.path=${logging.file.path}

 logging.path在不配置的情况下，是否可以兜底用 logging.file.path

**Comment by zjulbj** [comment]
#249 fixed
