### ISSUE TITLE
中间件与各种依赖适配逻辑的版本长期可维护性设计考虑

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#141]
## 问题描述
当前我们在对各种常见中间件和依赖做一些验证，如果验证有问题的，需要做一些多模块的适配。也就是我们的 sofa-serverless-adapter-ext bundle 的代码，但是这里暴露了一个问题：
不同 springboot 版本或 spring 版本，对应一些依赖例如 log4j2 的实现是不同的，那么 sofa-serverless-runtime 是否需要对不同的 springboot 或 spring 版本，提供不同的版本呢？那么 springboot 或 spring 版本这么多，这种方式显然是行不通的。

## 解决方案
当前有两种解决方案：
1. 类似 sofaboot，统一管控所有版本，包括了 springboot spring 的版本，但是这样的化，相当于做了一个对标 springboot 的研发框架了，对用户的侵入感比较强，故不采用
2. 只支持部分springboot spring 版本，维护统一的版本映射关系记录在官方文档里。

对比，第一种对用户不用好，第二种需要用户只能使用特定版本的 springboot 或 spring 版本。权衡利弊，不希望把 sofa serverless  做成太强势的研发框架，希望用户在自身代码基础上直接引入 sofa serverless 即可，所以还是采用方式 2.

**Comment by lylingzhen** [comment]
我也倾向方案二，只要用户 SpringBoot 应用引入我们支持的中间件版本就好。
我们未来可以提供一键修改 pom 工具、一键校验依赖版本兼容性工具等，把工具链做好，能方便的让用户一键修改版本即可。
