### ISSUE TITLE
Module Controller 核心流程设计

### ISSUE THREAD

**Issue by gold300jin** [sofastack/sofa-serverless#144]
### 模块生命周期
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/16ec7808-eab9-4293-b9c2-cddda3de5d85)

### 模块状态机
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/d06c10d6-1d37-48a9-9af3-0d44a6d7e1fd)

### 模块首发流程
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/6e076295-84b4-4611-98f6-04d8e953c0c2)

### 模块二发流程
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/2a38e0bb-32d0-403a-80aa-074eda3f97a4)

### 模块缩容流程
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/48e74dc9-7488-4fbf-b658-0bcf60a8a369)

### 基座替换流程
![image](https://github.com/sofastack/sofa-serverless/assets/13743483/a9586714-c44b-46e4-8a2f-0eefcac9cbca)

**Comment by lvjing2** [comment]
可以补充到官网里 https://github.com/sofastack/sofa-serverless/tree/master/docs/content/zh-cn/docs/contribution-guidelines/module-controller
