### ISSUE TITLE
installBiz 接口不需要传 bizName、bizVersion，改成从jar包里提取

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#147]
## 问题描述
当前安装模块需要额外传 bizName bizVersion, 实际上 jar 包里已经包含了这部分信息，如果这两处信息不一致，容易造成困惑。

![image](https://github.com/sofastack/sofa-serverless/assets/3754074/ed5cc552-9d70-4393-b810-54fb47c7ab7a)

## 方案
installBiz 接口不需要传 bizName、bizVersion，改成从jar包里提取

**Comment by TomorJM** [comment]
看了 #207 和 #211 的解决方法, 思路都是在handler处理的时候将文件中的name和version为主进行向后传递。
这个逻辑想了下可以换一种解决方式, 就是入参依旧接受name和version, 由上层调度侧传入, 在执行handler前validate的时候需要校验下传入的name和version和file解析出来的name和version是否一致, 如果不一致arklet返回安装失败并给出具体原因

@lvjing2 @sususama

**Comment by yuanyuancin** [comment]
在实际主站运用中，存在同一个模块Jar但是需要通过运维下发version来指定不同version的使用场景，建议开源继续保留，不要完全从jar中提取

**Comment by yuanyuancin** [comment]
> 在实际主站运用中，存在同一个模块Jar但是需要通过运维下发version来指定不同version的使用场景，建议开源继续保留，不要完全从jar中提取

同样的模块构建产物（biz1:version1），可能需要在JVM中存在多 BizModule 实例 (biz1:version1-0，biz1:version1-1)，以支持比如流量隔离等场景的灵活部署诉求，可以通过运维参数中不同的version1-0，version1-1来创建不同的biz实例

**Comment by lvjing2** [comment]
@TomorJM @sususama @kdcc 根据我们的经验，在内部是存在打包的 jar 版本，可运维的 jar 版本不完全一样的情况。所以也没法做前置的校验。
和 @yuanyuancin 说的类似，在内部，我们一次打包出来的 jar，可能被关联到不同的运维场景上。例如流量组，那么运维的时候，传递过来的 bizVersion 实际是 jar 里的 bizVersion + 流量组 ID , 那么这样就无法再 validate 做校验了。

那么这样的话，结论是，这个需求就不需要做什么代码逻辑修改和校验了。所以这个 issues 就关闭了。相应的 PR 也关闭掉。
