### ISSUE TITLE
SOFAServerless 1:1 通用基座模式支持重启容器来清空模块，而不是替换 Pod。速度更快。

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-serverless#158]
当前的 1:1 通用基座模式，新模块安装好后，老模块所在的 Pod 会被 Delete，触发 K8S 重建 Pod 从而达到删除上面模块的能力。我们需要加一个运维特性，比如：

uninstall-policy: restart
可以取值为 restart 或 replace，默认值为 restart。

取值 replace 就是现在 goldjin 实现的逻辑，删除老 Pod。
取值 restart 是需要新增的逻辑，通过修改容器的 ENV（比如把 restart-control-hash env 赋值为 1 个随机数），从而实现重启老容器，来达到卸载模块的目的。

**Comment by lylingzhen** [comment]
@gold300jin 关注。

**Comment by lvjing2** [comment]
新版k8s 不支持修改env，重启发布暂不支持
