### ISSUE TITLE
jaspyt 客户端适配 SOFAServerless 合并部署模式

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-serverless#164]
jaspyt 的这些适配（注册事件、联动 jaspyt 的 refresh），可以贡献一个适配器的 PR 到社区，让其他企业都能复用该贡献。

具体可参考 SOFAServerless log4j 的适配器代码：https://github.com/sofastack/sofa-serverless/blob/master/sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-log4j2/src/main/java/com/alipay/sofa/serverless/log4j2/SOFAServerlessLog4j2SpringContextListener.javalog4j 
![image](https://github.com/sofastack/sofa-serverless/assets/101314559/696377b9-8016-4a0f-a8d4-67d21f2741c2)

适配的原理在官网文档：https://github.com/sofastack/sofa-serverless/blob/master/docs/content/zh-cn/docs/contribution-guidelines/runtime/logj42.md

**Comment by lvjing2** [comment]
通过支持 spring cloud 来解决
