### ISSUE TITLE
官网 UI 更新与更换部署站点

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#173]
https://sofaserverless.netlify.app/
1. 当前 UI 还不符合蚂蚁统一风格，需要前端根据最新统一设计调整官网。
2. 当前站点偶尔不太稳定，启动较慢，发现是因为打开页面会有 google analysis，可以去掉改依赖，帮助启动加快。
3. 部署到新的站点

**Comment by lylingzhen** [comment]
已上线最新版官网，国内地址：https://sofaserverless.gitee.io/home/
