### ISSUE TITLE
补充 ModuleController 详细操作文档

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#178]
当前涉及到集群里的模块的操作还没有文档，需要补充下
1. 查看某个基座的所有模块
2. 查看某个机器上的模块信息和状态
3. 扩缩容
4. 更新部署
5. xxx 
@gold300jin 补充其他涉及到的用户操作的命令

**Comment by liu-657667** [comment]
### 查看某个基座上所有安装的模块名称和状态
```
kubectl get module -n <namespace> -l serverless.alipay.com/base-instance-ip=<pod-ip> -o custom-columns=NAME:.metadata.name,STATUS:.status.status
```
或
```
kubectl get module -n <namespace> -l serverless.alipay.com/base-instance-name=<pod-name> -o custom-columns=NAME:.metadata.name,STATUS:.status.status
```
### 查看某个基座上所有安装的模块详细信息
```
kubectl describe module -n <namespace> -l serverless.alipay.com/base-instance-ip=<pod-ip>
```
或
```
kubectl describe module -n <namespace> -l serverless.alipay.com/base-instance-name=<pod-name>
```

替换<pod-ip>为需要查看的基座ip，<pod-name>为需要查看的基座名称，<namespace>为需要查看资源的namespace

### 扩缩容操作
1. 修改ModuleDeployment资源下spec.replicas，增大参数值为扩容，减少参数值为缩容。
2. ModuleDeployment资源下spec.replicas的值要跟基座实例个数保持一致。

### 更新部署
1. 同时修改或修改其中ModuleDeployment资源下方字段将触发模块更新操作，会卸载上个版本的模块，安装新版本模块
   1. spec.template.spec.module.name 
   2. spec.template.spec.module.version
2. 如果只更新下方字段，将触发强推基线操作，当替换基座时才会根据url地址安装模块
   1. spec.template.spec.module.url
