### ISSUE TITLE
SOFAServerless 各组件 Release notes 与最新发布计划

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#19]
# SOFAArk 

## release 2.2.2 ，8月 release，计划发布内容

- DeclaredMode 支持 java -jar 模式运行，修复多级（超过3级）内嵌jar的 artifact 提取
- 支持 SOFABoot 4.0 https://github.com/sofastack/sofa-ark/issues/682
- zip file 安全问题修复，https://github.com/sofastack/sofa-ark/pull/565

# ModuleController
## release 0.3 ，8月 release，计划发布内容

- 模块发布、卸载、扩缩容、副本保持、基座运维联动
- 回滚链路、各项参数校验、单测达到 80/60、8+ 集成测试、CI 自动化、开发者指南

# Arklet
## release 0.1，8月 release
- Arklet 开发测试与CI环境
- Arklet 基础运维版本 https://github.com/sofastack/sofa-serverless/pull/11
- Arklet 锁控制

# ArkCtl

- ArkCtl 简单代码框架
- ArkCtl 开发测试与 CI 环境

**Comment by lylingzhen** [comment]
所有 Release Notes 详见：https://github.com/sofastack/sofa-serverless/releases
