### ISSUE TITLE
支持模块定义  RPC Filter

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#206]
## 问题描述
SPI 的定义与实现，往往是放在不同地方完成的。一个普遍场景是，基座里定义 SPI ，各个模块去实现 SPI 不同的实现。但这样会遇到一些类查找和转换的失败

## 问题解决方案
待确定

**Comment by qixiaobo** [comment]
目前发现当执行多模块telnet动态安装的时候 
存在线程classloader泄露的情况 导致classloader无法加载到指定biz的资源
典型场景目前为多biz 支持dubbo的rpcFilter
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/817af270-9d69-4a44-be55-2bbb4309ced8)

使用dubbo版本 2.6.12
其中hack了dubbo的ExtensionLoader

'''java

    private static ClassLoader findClassLoader() {
        //add by qixiaobo start support classloader
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        if(classLoader!=null) return classLoader;
        //add by qixiaobo end
        return ExtensionLoader.class.getClassLoader();
    }
'''

dubbo使用懒加载 端口号公共为20880
复现case:
安装biz1 其中biz1包含部分rpcFilter
安装biz2 其中biz2包含原biz1中没有的filter
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/6ba8e0bc-31d1-4971-abc5-22a8b554cc0b)

我们发现当前调用Biz时其中netty线程被污染 保留了biz1的ClassLoader
继而无法加载到biz2的资源 导致出错

**Comment by qixiaobo** [comment]
https://www.cnblogs.com/throwable/p/12216546.html

**Comment by zjulbj** [comment]
## dubbo 2.6.x Extension扩展机制相关问题（更新中）
### 1、com.alibaba.dubbo.common.extension.ExtensionLoader
findClassLoader是直接拿ExtensionLoader
```
 private static ClassLoader findClassLoader() {
      return ExtensionLoader.class.getClassLoader();
  }
```
### 2、SpringExtensionFactory
SpringExtensionFactory会遍历所有biz
```
 public <T> T getExtension(Class<T> type, String name) {
        for (ApplicationContext context : contexts) {
            if (context.containsBean(name)) {
                Object bean = context.getBean(name);
                if (type.isInstance(bean)) {
                    return (T) bean;
                }
            }
        }
```

**Comment by zjulbj** [comment]
#279 支持了2.6的版本

**Comment by lvjing2** [comment]
已完成
