### ISSUE TITLE
改进静态合并部署方案

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#213]
## 问题描述
当前 SOFAArk 提供的静态合并部署，是将 ark biz 在 pom 里定义。这样会导致两个问题：
1. ark biz 里的依赖会被基座引入，可能影响基座实际的依赖关系
2. ~~如果不同 ark biz 的 artifactId 是一样的 （groupId 不同），则会导致打包产物的 ark biz 相互覆盖，因为都是放在相同目录 lib 下。~~
3. 需要将 ark biz 上传到 mvn 仓库，在某些公司没有私有的 mvn 仓库，则该方案基本不可行。

## 解决方式
建设基于配置的静态合并部署方案

1. 在基座的配置文件中，增加定义需要静态部署的 ark biz 列表
2. 打包基座的时候，将这些 ark biz 从对应的仓库中心（例如 oss）中下载下来，构建到基座镜像里
3. 基座启动的时候，从镜像某个目录里查找到 ark biz，并启动这些biz

**Comment by qixiaobo** [comment]
不可变基础设施是一种构建和管理系统的方法，其中系统组件在部署后是不可更改的。在这种基础设施中，任何更改都需要通过重新构建和部署来实现。打包静态化部署是不可变基础设施的一个关键方面，它强调将应用程序的所有依赖项和配置打包成一个不可更改的部署包，然后将其部署到目标环境中。

以下是描述打包静态化部署重要性的几个关键原因：

一致性和可重复性：打包静态化部署确保每次部署都是基于相同的部署包进行的，这消除了部署过程中的变化和不确定性。这种一致性和可重复性对于构建可靠的、可预测的系统至关重要。

部署速度和可伸缩性：通过将所有依赖项打包到一个部署包中，打包静态化部署可以显著减少部署时间。这是因为它避免了在每次部署时下载和安装依赖项的过程，而只需将部署包复制到目标环境即可。此外，由于部署包是独立的，可以轻松地进行水平扩展，以满足不同规模和负载要求。

可控性和回滚能力：由于打包静态化部署是不可更改的，可以更轻松地管理系统的状态。如果出现问题，可以简单地回滚到先前的部署包，而不必担心系统状态的复杂变化。这提供了更好的可控性和可恢复性，减少了故障恢复时间和风险。

安全性：打包静态化部署可以提高系统的安全性。通过减少对部署环境的依赖性，可以降低潜在的漏洞和攻击面。此外，由于部署包是不可更改的，它们可以通过数字签名或哈希校验来验证其完整性和真实性，以确保没有被篡改或替换。

**Comment by sususama** [comment]
Assigned To Me, pls

**Comment by CodeNoobKing** [comment]
I would like to check this issue.

**Comment by qixiaobo** [comment]
1.可以通过maven的exclude排除 如下
 <dependency>
            <groupId>com.xxx.xxx</groupId>
            <artifactId>web</artifactId>
            <classifier>ark-biz</classifier>
            <version>0.0.1-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

注意传递依赖的通配符排除的支持从maven3.2.1支持 https://maven.apache.org/docs/3.2.1/release-notes.html#transitive-dependency-excludes-mng-2315

**Comment by qixiaobo** [comment]
2.当出现同名文件 即artifactId classifier version相同 但是groupId不同的场景 此时springboot已经原生支持 会自动rename
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/2b3474d1-d37d-46f1-88b9-d38a73718c7a)
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/c02c779b-c2fb-4056-86a3-eb22b001ef88)
