### ISSUE TITLE
模块与 springboot 构建产物重复

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#221]

**Comment by qixiaobo** [comment]
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/9d185e15-dbc5-4451-80e0-8866c829286e)

接入了sofa的maven组件之后发现打包出来的ark-biz非常大
原因是springboot的插件也在repackage阶段
注意:
有可能是父pom定义的 如果无法修改父pom
可以考虑skip掉springboot的repackage
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/92d9d596-8716-4749-824a-dd20d5979701)

```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <executions>
    <execution>
      <goals>
        <goal>repackage</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <skip>true</skip>
  </configuration>
</plugin>
```

注 此版本使用springboot 1.5.10的maven打包插件

**Comment by lvjing2** [comment]
可考虑是否是 springboot 版本问题

**Comment by lvjing2** [comment]
未能复现

**Comment by qixiaobo** [comment]
使用springboot1.5 demo如下
![image](https://github.com/sofastack/sofa-serverless/assets/2881751/a5d55a2a-2394-46a6-bcb4-c70f933fd001)
https://github.com/qixiaobo/springboot-demo-1.5-test-ark-package
