### ISSUE TITLE
验证中间件列表，补充 samples 用例

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#232]
1. spring cloud gateway, 同时也验证下这个issue https://github.com/sofastack/sofa-ark/issues/699
- [x] webflux & netty
3. undertow
- [x] rocketmq
6. skywalking

**Comment by qixiaobo** [comment]
3. undertow是springboot里加进来的依赖自动激活的 只要在排包的时候去掉就OK了 
undertow不支持单host 此外也需要注意原先的配置参数比如iothreads是否支持或者改动
