### ISSUE TITLE
[FEATURE] 关于 arklet 健康检查解决方案

### ISSUE THREAD

**Issue by Lunarscave** [sofastack/sofa-serverless#25]
## 关于 arklet 健康检查解决方案

version: 0.0.1
### 0、需求

* arklet 中编排健康检查与心跳上报指令
* 在jvm和spring中考虑健康检查
* 心跳上报考虑宿主与biz模块、子应用的状态感知（暂未在本期考虑）

主要的思路：
* 设计模块Arklet Actuator，最开始可以通过 properties 控制是否打开监控
* 与 Springboot Actuator 对接，设定时间间隔写到日志，调用时从日志（elastic.logstash）中读取。
* Health Checker Processor 负责 Health Check Handler 的调度
* 在上游发起 Http 请求时，UnifiedOperationServiceImpl 调用 Health Check Processor 获取最新健康检查信息
* 设置 flashback 时间，所有 Arklet Actuator 配置写在 Auto Health Checker Configuration

### 1、指令层设置

* `/metrics`：查询 spring + JVM 健康度

* `/health` ：查询对应 biz 的心跳（maybe SOFA Boot）

```JSON
{
"bizName": "dynamic-provider",
"bizVersion": "1.0.0"
}
```

### 2、控制层

主要设计：

![202308141839.png](https://picgo-1313342257.cos.ap-nanjing.myqcloud.com/test/202308141839.png)
* `MetricHandler` 同内置指令
* 将 Health Checker Processor 注入 UnifiedOperationService，提供统一接口调用 Metrics Checker Handler （抽象是 Health Checker Handler，负责下期的 biz 模块 BizHealth Checker Handler）
* `Metrics Info` 作为每个健康检查的 Meta Data
* `Actuator Callback` 健康检查后回调
* `Auto Health Checker Configuration` springboot 启动配置等
* `Metrics Checker Handler`
	* 装配 Metrics Info 成 Response
	* （解析 Request 中 BizModel）
	* 响应 CallBack
	* 读取日志最新检查信息

初始化的流程：

![202308141904.png](https://picgo-1313342257.cos.ap-nanjing.myqcloud.com/test/202308141904.png)

完成一次请求的流程：

![202308141900.png](https://picgo-1313342257.cos.ap-nanjing.myqcloud.com/test/202308141900.png)

**Comment by yuanyuancin** [comment]
模块运维关联管理Pod整体Ready状态
