### ISSUE TITLE
支持导出基座依赖的pom方便模块瘦身

### ISSUE THREAD

**Issue by zjulbj** [sofastack/sofa-serverless#254]
模块瘦身时，经常需要判断基座有哪些依赖，需要有一个机制方便的看到基座的依赖列表，方便瘦身
比如这样：
![image](https://github.com/sofastack/sofa-serverless/assets/2871725/2046d64b-8c2b-4a71-9363-c464635c7c4a)

**Comment by lvjing2** [comment]
两个方案各有优劣：
### 基于 rules.txt 的排包方案
#### 优势
1. 模块使用比较简单，只需导入即可
#### 劣势
1. 如果基座没有依赖，而模块里又被自动排包掉，需要基座再额外引入进来。
2. 模块可能排包过多，例如 org.springframework.* 的部分希望 compile 依赖，则没有很好支持方式。

### 基于基座 pom依赖列表的排包方案
#### 优势
与基座的依赖关联比较紧密，不会出现模块拍完包之后，运行时找不到依赖的问题

#### 缺陷
1. 基座的依赖会改变
3. 基座与模块关联太强
4. 模块手动排包成本太高，模块自动排包则需要提供允许自动以不排包的方式

**Comment by lvjing2** [comment]
考虑方案一的设计初衷，就是放入必须下沉基座的依赖，同时也兼顾简化使用。所以对于方案一的两个问题，可以考虑如果基座缺失依赖，则让基座添加依赖；如果排包过多，只要不影响启动的就默认排包掉，如果是影响启动的，则需要修改配置从而支持默认不拍影响启动的包。

考虑方案二，一定需要具备自动化排包能力，如果使用自动化排包能力，目前看不方便给用户自定义配置不排包依赖。另外模块需要pom里引入基座 bom，导致模块改造成本存在与基座代码耦合的行为，导致改造成本变高。另外由于基座依赖的变动，以及存在基座多个分支里如果依赖不同的情况，可能出现不在预期的问题。

所以综合考虑，继续采用方案一，遇到方案一的两个问题，第一个问题由用户增加基座依赖解决，第二个问题继续强制排包掉（除非排包会导致启动失败，则修改 rules.txt 配置文件）

**Comment by lvjing2** [comment]
结论，两种作为不同场景提供能力，供选择使用：
1、rule.txt：不需要知道基座依赖，也对基座依赖的版本不敏感，想快速迁移瘦身的模式
2、pom：尽量复用基座依赖，彻底瘦身，想知道基座哪些已经有了，新建的模块
