### ISSUE TITLE
Arklet 排障性增强

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#263]
## 问题描述
当前一些情况，如果模块安装失败，arklet不会返回日志，只会打印这段信息
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/41931aa8-f064-431a-8b6a-c72b604c2f5b)

## 目标
模块安装失败，能直接看到失败的原因和日志

**Comment by TomorJM** [comment]
这个期望是在安装失败情况下, arklet能够输出详细异常信息到log里?

**Comment by lvjing2** [comment]
> 这个期望是在安装失败情况下, arklet能够输出详细异常信息到log里?

是的，有两个点：
1. 日志终端和文件里能打印出失败的原因和堆栈
2. arklet 能够返回错误信息和堆栈给上游调用方

**Comment by sususama** [comment]
Assign it to me, pls

**Comment by lvjing2** [comment]
现在麻烦在这里打断点查看详细堆栈和错误信息
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/cbf10b14-2be8-4e13-a1b5-2062373ab3ea)

**Comment by TomorJM** [comment]
优化了这里的逻辑
