### ISSUE TITLE
模块安装支持不传递bizName、bizVersion

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-serverless#325]
### Feature description
考虑从 SOFAArk 里提供更原子的 api，避免模块重复下载解压的耗时

### Additional notes

Add other notes if necessary.

开源 SOFAServerless 只支持先卸后装（先不考虑裸用 SOFAArk 的场景），所以可以简化很多。直接在 Arklet 里解析出版本号，自动填入 version，传给 SOFAArk，SOFAArk 不用改。

**Comment by sususama** [comment]
#170 这个PR可以解决这个问题吗？

**Comment by lvjing2** [comment]
@TomorJM

**Comment by lvjing2** [comment]
安装模块推荐增加该配置，如果没有也允许，退化从jar里提取。但是给出警告，会有性能损失。
