### ISSUE TITLE
资源方面如何做隔离呢

### ISSUE THREAD

**Issue by siaron** [sofastack/sofa-serverless#359]
### Describe the question or bug

分模块开发后，运行时基座和模块在一个jvm内。有没有针对模块资源做隔离的方法，不让模块和基座相互影响

### Expected behavior

模块独立的cpu，内存隔离

**Comment by siaron** [comment]
类似这个 https://github.com/sofastack/sofa-ark/issues/802?notification_referrer_id=NT_kwDOANEQcLM4NjA5MTU1NDExOjEzNzAxMjMy 租户可能会自己注册一个模块，想和基座隔离开不受影响。但还是一个应用内，可以访问到其他的一些资源

**Comment by lvjing2** [comment]
如上面说的，对于 cpu 和 memory 的隔离目前是没有很强的实际使用需求的。除非你是公有云平台方，才考虑强隔离。我们这套模式有个很重要的优势也是因为我们的cpu 和memory可以共享才能把性能和资源消耗降到极致的。因此，如果要考虑隔离，麻烦把为什么需要隔离的场景描述清楚，确认是不是我们这边还未知的实际需求。
