### ISSUE TITLE
Slf4j2 + Logback1.3 支持 Biz日志配置隔离

### ISSUE THREAD

**Issue by yuanyuancin** [sofastack/sofa-serverless#403]
当前 支持多biz日志配置隔离的功能依赖 logback 原生 ContextSelector 机制 （com.alipay.sofa.ark.common.adapter.ArkLogbackContextSelector）

SpringBoot3 默认使用 Slf4j2 + Logback1.3.x 作为日志打印框架，Slf4j2 相较 Slf4j 弃用了 StaticLoggerBinder，改为了 Java SPI ServiceLoader 机制进行日志实现框架绑定，该机制不支持 ContextSelector 特性（ch.qos.logback.classic.spi.LogbackServiceProvider）

![image](https://github.com/sofastack/sofa-serverless/assets/16517325/9bad6073-7c7e-4bef-98dc-4650161b61bc)

**Comment by lvjing2** [comment]
已完成 #471
