### ISSUE TITLE
autoconfigure引起的class not find

### ISSUE THREAD

**Issue by chenlei3641** [sofastack/sofa-serverless#409]
<java.version>8</java.version>
<sofa.ark.version>2.2.4</sofa.ark.version>
<sofa.serverless.runtime.version>0.5.5</sofa.serverless.runtime.version>
<spring.boot.version>2.7.15</spring.boot.version>

![A9081D50-F77F-404c-866E-5690680F672C](https://github.com/sofastack/sofa-serverless/assets/38515827/f23ba68c-1cab-44f8-bda6-235707a04e02)

如图，
1、当模块启动时，会扫描到基座中存在autoconfigure的jar；
2、这里的自动配置根据ConditionalOnClass来触发配置；
3、当biz中存在条件中的类时就会加载autoconfigure的类；
4、但是由于autoconfigure的类是基座cl加载的，并依赖了模块范围内的类，就出现了向上反找class的问题。

**Comment by lvjing2** [comment]
如上所说，模块里 provided 引入了 JCacheCache 和 CacheManager 两个类，触发了 JCacheCacheMeterBinderProviderConfiguration 的初始化，然后在创建 JCacheCacheMeterBinderProvider bean 的时候，到目前为止这些类都是在模块里有声明的。但是在初始化 JCacheCacheMeterBinderProvider 该对象依赖的其他类时，触发了从基座反向查找某一些模块上的类的问题，导致 ClassNotFound。

`如 Class.forName("模块类名")，没有制定 classLoader, 则默认从当前类所在 classLoader 查找，也就是基座 ClassLoader`

**Comment by lvjing2** [comment]
当前可能的解决方式：
1. 模块 compile JCacheCacheMeterBinderProviderConfiguration 相关依赖 （如果有问题可以把基座里这个依赖去掉）
2. 模块 main 里 exclude JCacheCacheMeterBinderProviderConfiguration
3. 基座里统一配置 exclude AutoConfiguration 黑名单
