### ISSUE TITLE
补充 Arklet 代码注释、单元测试和面向社区共建同学的设计文档

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-serverless#42]

**Comment by TomorJM** [comment]
![img](https://github.com/sofastack/sofa-serverless/assets/11410549/6a890bec-0c62-403a-81e4-ee0e6246ad23)

**Comment by TomorJM** [comment]
![yuque_diagram](https://github.com/sofastack/sofa-serverless/assets/11410549/7865e417-6909-4e89-bd48-c926162eaf83)

**Comment by TomorJM** [comment]
https://github.com/sofastack/sofa-serverless/tree/master/arklet
