### ISSUE TITLE
恭喜祁晓波成为 SOFAServerless 优秀 Contributor

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#425]
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/020a3e7e-d4dd-45bc-8fc2-bf3d8d2f3cd5)

[祁晓波](https://github.com/qixiaobo) 作为F6汽车科技基础设施负责人，主要研究微服务、可观测、稳定性、研发效能、java中间件等领域

自加入 SOFAServerless 项目以来，他贡献了诸多框架与中间件在多模块模式下的最佳实践和治理方案，并从框架角度一起探讨如何以更标准化、可持续性的解决思路和方案，也贡献了 dubbo、apollo 等的 adapter 组件。

2023 年 12 月26日，SOFAServerless 社区PMC之一 赵真灵 代表 SOFAServerless 社区，宣布 祁晓波 @qixiaobo  通过投票，成为社区优秀 Contributor！

### commits 记录/PR 贡献等：
https://github.com/sofastack/sofa-serverless/pulls?q=is%3Apr+is%3Aclosed+author%3Aqixiaobo
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/7bf9d823-7eb5-408a-8a8e-97311a3a9e2e)

https://github.com/sofastack/sofa-ark/pulls?q=is%3Apr+is%3Aclosed+author%3Aqixiaobo
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/d5da2e43-a21b-4470-8ad6-17818383b98f)

### 突出贡献：
扩展了 springboot 1.x 的支持，沉淀了10+类组件在落地多应用模式的最佳实践和治理方案，并深度参与如何从框架角度定义标准治理方案，完成了 dubbo 2.6 和 apollo 的 adapter 适配组件。
![image](https://github.com/sofastack/sofa-serverless/assets/3754074/1b4df0a0-d767-4e9b-bf11-488910e8dd1f)

### 成员感想
很荣幸和 SOFA 一起为开源社区打造一款基于 spring/springboot/sofaboot 的 serverless 框架。目前越来越多的企业在支持海量微服务之后感受到了微服务对于架构复杂度的不友好，尤其是在成本支出这块。现在 ESG 在整个社会越发得到重视，国家也在大力发展绿色经济，无数人在为碳中和付出自己的努力。也特别有幸在这个环节可以为 java 生态添砖加瓦，期望可以更好的和社区合作共建。

### 社区同学寄语
感谢祁晓波一直以来为 SOFAServerless 项目做出的巨大贡献！期待未来和晓波一起，让 SOFAServerless 变得更好！

同时感谢各位对 SOFAServerless 社区的贡献，也希望更多的小伙伴加入 SOFAServerless 社区，共同助力开源环境的快速发展。

**Comment by khotyn** [comment]
Congrats~

**Comment by TomorJM** [comment]
Nice 💐
