### ISSUE TITLE
Arklet 支持 JDK17

### ISSUE THREAD

**Issue by lylingzhen** [sofastack/sofa-serverless#48]
单测在 JDK17 环境跑过。

**Comment by sususama** [comment]
这个是哪里报错吗？我在我本地使用`mvn test`并没有报错

**Comment by lylingzhen** [comment]
你的 JDK 确定是 JDK17 吗？

**Comment by sususama** [comment]
> 你的 JDK 确定是 JDK17 吗？

是的

**Comment by lylingzhen** [comment]
那你先关掉吧，可能是我环境问题。等有用户上报再重开。

**Comment by sususama** [comment]
> 那你先关掉吧，可能是我环境问题。等有用户上报再重开。

这个可能跟SOFAARK那边一样，我test通过是先package跳过test，然后打包完成以后再test就能通过
