### ISSUE TITLE
moduleDeployment QuickStart和demo说明文档

### ISSUE THREAD

**Issue by gold300jin** [sofastack/sofa-serverless#52]

**Comment by liu-657667** [comment]
## QuickStart
1. 下载go 1.20.5/ Docker/ Minikube/ kubectl
2. 拉取sofa-severless项目，在/sofa-serverless/module-controller目录下执行make dev一键部署环境，会自动执行minikube service 命令弹出网页，当前网页会没有效果展示。
3. kubectl apply -f config/samples/module-deployment_v1alpha1_moduledeployment.yaml安装模块
4. 模块扩容，将上方路径内yaml文件的replicas字段的值增大后kubectl apply -f，模块缩容，减小replicas字段的值
5. 等待Module资源Status更改为Available，刷新自动打开的网页，效果如下图所示
<img width="813" alt="image" src="https://github.com/sofastack/sofa-serverless/assets/41184355/3757406d-ed83-4556-9aec-fa3b7fdb8c55">

6. make undev删除部署资源，清理本地环境

**Comment by liu-657667** [comment]
add quickStart video
https://github.com/sofastack/sofa-serverless/assets/41184355/fb31f111-84ff-46e8-9e5f-2d953db9891b
