### ISSUE TITLE
建设 playGround 快速试用能力

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#6]
结合[开源大讲堂](https://www.oscollege.net/product)，建设快速试用。
1. 部署常驻基座
2. 提供快速创建模块的入口
3. 能发起简单部署
5. 发起流量调用
6. 具备一定的验证

**Comment by lylingzhen** [comment]
另外，官网可以选型 https://pages.github.com/ （但网络可能不好）；或者参考 Kapacity 使用的托管网站；或者用某个框架自己搭一个部署到阿里云。

**Comment by lylingzhen** [comment]
直接使用 @liu-657667 的本地一键快速开始能力，目前看不再需要 PlayGround。
