### ISSUE TITLE
[Module Controller] 通过 K8S Service 方式实现模块、基座的流量联动 [单测+集测]

### ISSUE THREAD

**Issue by gold300jin** [sofastack/sofa-serverless#64]
至少能支持模块首发、二发、下线自动创建、更新、删除关联的 K8S Service 资源。

**Comment by lylingzhen** [comment]
至少能支持模块首发、二发、下线自动创建、更新、删除关联的 K8S Service 资源。

**Comment by lylingzhen** [comment]
集测已完成 1 个热部署发布主链路，余下的后面排期。close。
